"""Add description field to ResumeField

Revision ID: 317500e85b84
Revises: 88b625a3cf68
Create Date: 2025-06-23 07:12:36.707228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317500e85b84'
down_revision = '88b625a3cf68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
