"""Add label and value fields to ResumeField

Revision ID: 88b625a3cf68
Revises: 8d1eca5b886e
Create Date: 2025-06-23 07:06:09.824739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88b625a3cf68'
down_revision = '8d1eca5b886e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('value', sa.String(length=500), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('label_translations')
        batch_op.drop_column('value_translations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('label_translations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('value')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
