"""Add translations fields to ResumeField

Revision ID: 8d1eca5b886e
Revises: 
Create Date: 2025-06-23 05:04:08.603929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d1eca5b886e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_translations', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('key')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('label_translations')

    # ### end Alembic commands ###
