name: PostgreSQL Status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # كل 12 ساعة

jobs:
  check-db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: 🧰 Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: 🧪 Check PostgreSQL connection
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c '\l'
